- name: Configure Api Definition
  hosts: webservers
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: create api definition
      api_definition:
        state: present
        metadata:
          namespace: "default"
          name: "demo-api-def"
        spec:
          swagger_specs:
            - "{{ swagger_file.metadata.url }}" # see stored_object.yaml
      register: api_definition