- name: Manage API Credentials
  hosts: webservers
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: create vk8s credentials
      api_credentials:
        state: present
        expiration_days: 5
        name: "demo-credentials"
        spec:
          api_type: "KUBE_CONFIG"
          virtual_k8s_name: "vk8s"
          virtual_k8s_namespace: "default"
      register: credentials

    - name: revoke vk8s credentials
      api_credentials:
        state: absent
        name: "{{ credentials.name }}"