- name: Configure TCP or HTTP Health Check
  hosts: all
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: fetch current tenant details
      fetch_tenant_settings:
      register: tenant

    - name: create http health monitor
      health_check:
        state: present
        metadata:
          namespace: "default"
          name: "demo-http-health-check"
        spec:
          healthy_threshold: 0
          http_health_check:
            expected_status_codes:
              - "200"
            headers:
              Hostname: Demo-Host
            path: "/"
            request_headers_to_remove:
              Hostname: Demo-Host
            use_http2: true
            use_origin_server_name: {}
          interval: 0
          jitter_percent: 0
          tcp_health_check:
             expected_response: "00000034"
             send_payload: "000000FF"
          timeout: 0
          unhealthy_threshold: 0
      
    - name: create tcp health monitor
      health_check:
        state: present
        metadata:
          namespace: "default"
          name: "demo-tcp-health-check"
        spec:
          healthy_threshold: 0
          interval: 0
          jitter_percent: 0
          tcp_health_check:
             expected_response: "00000034"
             send_payload: "000000FF"
          timeout: 0
          unhealthy_threshold: 0

    - name: delete http health monitor
      http_health_check:
        state: absent
        metadata:
          namespace: "default"
          name: "demo-http-health-check"
        spec:

    - name: delete tcp health monitor
      http_health_check:
        state: absent
        metadata:
          namespace: "default"
          name: "demo-tcp-health-check"
        spec: