- name: Configure HTTP Load Balancer
  hosts: webservers
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: fetch current tenant details
      fetch_tenant_settings:
      register: tenant

    - name: create load balancer
      http_loadbalancer:
        state: present
        metadata:
          namespace: "default"
          name: "demo-http-lb"
        spec:
          domains:
            - "example.com"
          http:
            port: 80
          default_route_pools:
            - pool:
                tenant: "{{ tenant.name }}"
                namespace: "default"
                name: "demo-origin-pool"
              weight: 1
              priority: 1

    - name: update load balancer with firewall details
      http_loadbalancer:
        state: present
        patch: True
        metadata:
          namespace: "default"
          name: "demo-http-lb"
        spec:
          disable_waf:
          app_firewall:
            tenant: "{{ tenant.name }}"
            namespace: "default"
            name: "demo-fw"

    - name: delete load balancer
      http_loadbalancer:
        state: absent
        metadata:
          namespace: "default"
          name: "demo-http-lb"
        spec: