- name: Configure Stored Objects
  hosts: webservers
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: upload swagger file
      stored_object:
        state: present
        string_value: "{{ lookup('file', '../swagger.json') | string }}"
        content_format: "json"
        name: "demo-swagger"
        object_type: "swagger"
        namespace: "default"
