- name: Configure Virtual Kubernetes
  hosts: webservers
  collections:
    - devd4n.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: create vk8s
      virtual_kubernetes:
        state: present
        wait: True
        metadata:
          namespace: "default"
          name: "demo-vk8s"
        spec:
          vsite_refs:
            - kind: "virtual_site"
              tenant: "ves-io"
              namespace: "shared"
              name: "ves-io-all-res"